name = "takahiroworld"
compatibility_date = "2025-07-07"

main = "worker/worker.js"
workers_dev = true

[site]
bucket = "./public"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = false



