name = "takahiro_world"
type = "javascript"

account_id = "474707b9f3c070db2946e0d268def24f"
workers_dev = true

[build]
upload.format = "modules"
upload.main = "worker/main.js"

[site]
bucket = "./public"
entry-point = "worker"
